#####
# This is an example of docker compose file for Apillon pre-built solutions. You are encouraged to change it according to your needs.
#####

version: '3.8'

services:
  nft_studio_db:
    image: mysql
    container_name: nft_studio_db
    ports:
      - '3306:3306'
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_POOL: ${MYSQL_POOL}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
      interval: 2s

  nft_studio_mail:
    image: bytemark/smtp
    container_name: nft_studio_mail
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
