import type { GlobalThemeOverrides, MessageProviderProps } from 'naive-ui';
import { colors } from '~/tailwind.config';

type MessageThemeOverrides = NonNullable<MessageProviderProps['themeOverrides']>;
const messageOverrides: MessageThemeOverrides = {
  borderRadius: '8px',
  closeIconColor: colors.black,
  closeIconColorError: colors.black,
  closeIconColorHover: colors.black,
  closeIconColorHoverError: colors.black,
  closeIconColorHoverInfo: colors.black,
  closeIconColorHoverLoading: colors.black,
  closeIconColorHoverSuccess: colors.black,
  closeIconColorHoverWarning: colors.black,
  closeIconColorInfo: colors.black,
  closeIconColorLoading: colors.black,
  closeIconColorPressed: colors.black,
  closeIconColorPressedError: colors.black,
  closeIconColorPressedInfo: colors.black,
  closeIconColorPressedLoading: colors.black,
  closeIconColorPressedSuccess: colors.black,
  closeIconColorPressedWarning: colors.black,
  closeIconColorSuccess: colors.black,
  closeIconColorWarning: colors.black,
  color: colors.bg.light,
  colorError: colors.bg.light,
  colorInfo: colors.bg.light,
  colorLoading: colors.bg.light,
  colorSuccess: colors.bg.light,
  colorWarning: colors.bg.light,
  iconColor: colors.black,
  iconColorError: colors.black,
  iconColorInfo: colors.black,
  iconColorLoading: colors.black,
  iconColorSuccess: colors.black,
  iconColorWarning: colors.black,
  maxWidth: '380px',
  padding: '24px',
  textColor: colors.black,
  textColorError: colors.black,
  textColorInfo: colors.black,
  textColorLoading: colors.black,
  textColorSuccess: colors.black,
  textColorWarning: colors.black,
};

/**
 * Theme configs
 */
export const NaiveTheme: GlobalThemeOverrides = {
  common: {
    baseColor: colors.grey.darker,
    bodyColor: colors.bg.dark,
    errorColor: colors.pink,
    fontFamily: 'Inter',
    fontSize: '14px',
    infoColor: colors.blue,
    primaryColor: colors.blue,
    primaryColorHover: colors.blue,
    primaryColorPressed: colors.blue,
    successColor: colors.green,
  },
  Alert: {
    border: `3px solid ${colors.pink}`,
    borderError: `3px solid ${colors.pink}`,
    borderInfo: `3px solid ${colors.blue}`,
    borderSuccess: `3px solid ${colors.green}`,
    borderWarning: `3px solid ${colors.pink}`,
    borderRadius: '8px',
    color: colors.bg.light,
    colorError: colors.bg.light,
    colorInfo: colors.bg.light,
    colorLoading: colors.bg.light,
    colorSuccess: colors.bg.light,
    colorWarning: colors.bg.light,
    contentTextColor: colors.black,
    contentTextColorError: colors.black,
    contentTextColorInfo: colors.black,
    contentTextColorSuccess: colors.black,
    contentTextColorWarning: colors.black,
    textColor: colors.black,
    textColorError: colors.black,
    textColorInfo: colors.black,
    textColorLoading: colors.black,
    textColorSuccess: colors.black,
    textColorWarning: colors.black,
    titleTextColor: colors.black,
    titleTextColorError: colors.black,
    titleTextColorInfo: colors.black,
    titleTextColorSuccess: colors.black,
    titleTextColorWarning: colors.black,
    titleFontWeight: '700',
  },
  Button: {
    border: `1px solid ${colors.grey.dark}`,
    borderDisabled: `1px solid ${colors.grey.dark}`,
    borderDisabledError: `1px solid ${colors.grey.dark}`,
    borderDisabledInfo: `1px solid ${colors.grey.dark}`,
    borderDisabledPrimary: `1px solid ${colors.grey.dark}`,
    borderDisabledSuccess: `1px solid ${colors.grey.dark}`,
    borderDisabledWarning: `1px solid ${colors.grey.dark}`,
    borderError: `1px solid ${colors.grey.dark}`,
    borderFocusError: `1px solid ${colors.pink}`,
    borderHoverError: `1px solid ${colors.pink}`,
    borderPressedError: `1px solid ${colors.pink}`,
    borderFocus: `1px solid ${colors.grey.dark}`,
    borderHover: `1px solid ${colors.grey.dark}`,
    borderPrimary: `1px solid ${colors.grey.dark}`,
    borderFocusPrimary: `1px solid ${colors.grey.dark}`,
    borderHoverPrimary: `1px solid ${colors.grey.dark}`,
    borderPressedPrimary: `1px solid ${colors.grey.dark}`,
    borderRadiusTiny: '0px',
    borderRadiusSmall: '8px',
    borderRadiusMedium: '8px',
    borderRadiusLarge: '8px',
    colorDisabledPrimary: colors.grey.dark,
    colorInfo: colors.white,
    colorHover: colors.grey.dark,
    colorHoverInfo: colors.white,
    colorFocusInfo: colors.white,
    colorPressedInfo: colors.white,
    colorDisabledInfo: colors.white,
    colorQuaternary: colors.transparent,
    colorQuaternaryHover: colors.transparent,
    colorQuaternaryPressed: colors.transparent,
    colorTertiaryHover: colors.grey.dark,
    colorTertiaryPressed: colors.grey.dark,
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    fontWeight: 'bold',
    heightTiny: '24px',
    heightSmall: '32px',
    heightMedium: '38px',
    heightLarge: '48px',
    paddingTiny: '1px',
    paddingSmall: '6px 12px',
    paddingMedium: '8px 16px',
    paddingLarge: '8px 24px',
    textColorError: colors.pink,
    textColorFocus: colors.white,
    textColorFocusError: colors.pink,
    textColorGhost: colors.black,
    textColorGhostHover: colors.black,
    textColorGhostPrimary: colors.black,
    textColorGhostDisabledPrimary: colors.black,
    textColorGhostFocusPrimary: colors.black,
    textColorGhostHoverPrimary: colors.black,
    textColorGhostPressedPrimary: colors.black,
    textColorHover: 'inherit',
    textColorInfo: colors.bg.dark,
    textColorHoverError: colors.pink,
    textColorGhostHoverError: colors.pink,
    textColorTextHoverError: colors.pink,
    textColorPressedError: colors.pink,
    textColorTextError: colors.pink,
    textColorTertiary: colors.white,
  },
  Card: {
    borderColor: colors.grey.transparent,
    borderRadius: '8px',
    color: colors.bg.dark,
    colorEmbedded: colors.bg.dark,
    colorEmbeddedModal: colors.bg.dark,
    colorEmbeddedPopover: colors.bg.dark,
    colorModal: colors.bg.dark,
    colorPopover: colors.bg.dark,
    colorTarget: colors.bg.dark,
    paddingSmall: '32px',
    paddingMedium: '16px 64px 16px 64px',
  },
  Checkbox: {
    color: colors.transparent,
  },
  DataTable: {
    borderColor: colors.black,
    borderColorModal: colors.black,
    tdColor: colors.transparent,
    tdColorHover: colors.transparent,
    tdColorHoverModal: colors.transparent,
    tdColorModal: colors.transparent,
    tdTextColor: colors.grey.dark,
    thColor: colors.bg.light,
    thColorHoverModal: colors.bg.light,
    thColorHoverPopover: colors.bg.light,
    thColorModal: colors.bg.light,
    thColorHover: colors.bg.light,
    thFontWeight: '700',
    thTextColor: colors.black,
  },
  Dialog: {
    border: `1px solid ${colors.grey.dark}`,
    borderRadius: '0px',
    closeBorderRadius: '50%',
    closeColorHover: colors.white,
    closeColorPressed: colors.white,
    closeIconColor: colors.white,
    closeIconColorPressed: colors.bg.dark,
    closeIconColorHover: colors.bg.dark,
    color: colors.bg.dark,
    contentMargin: '16px 0',
    titleFontSize: '20px',
  },
  Drawer: {
    color: colors.bg.DEFAULT,
  },
  Dropdown: {
    borderRadius: '8px',
    color: colors.bg.light,
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    optionColorActive: colors.grey.dark,
    optionColorHover: colors.grey.dark,
    // optionTextColor: colors.white,
    // optionTextColorHover: colors.white,
    // optionTextColorActive: colors.white,
    // optionTextColorChildActive: colors.white,
    padding: '16px 12px',
  },
  Form: {
    feedbackFontSizeSmall: '12px',
    feedbackFontSizeMedium: '12px',
    feedbackFontSizeLarge: '14px',
    feedbackHeightSmall: '24px',
    feedbackHeightMedium: '32px',
    feedbackHeightLarge: '40px',
    labelFontSizeTopSmall: '10px',
    labelFontSizeLeftSmall: '10px',
    labelFontSizeLeftMedium: '12px',
    labelFontSizeTopMedium: '12px',
    labelFontSizeLeftLarge: '14px',
    labelFontSizeTopLarge: '14px',
    labelPaddingVertical: '0 0 8px',
    labelTextColor: colors.black,
  },
  Input: {
    border: `1px solid ${colors.grey.dark}`,
    borderFocus: `1px solid ${colors.grey.darkerTransparent}`,
    borderHover: `1px solid ${colors.grey.dark}`,
    borderError: `1px solid ${colors.pink}`,
    borderFocusError: `1px solid ${colors.pink}`,
    borderHoverError: `1px solid ${colors.pink}`,
    borderDisabled: `1px solid ${colors.grey.darker}`,
    borderRadius: '8px',
    boxShadowFocus: 'none',
    boxShadowFocusError: 'none',
    boxShadowFocusWarning: 'none',
    caretColor: colors.black,
    clearSize: '24px',
    color: colors.transparent,
    colorDisabled: colors.transparent,
    colorFocus: colors.transparent,
    colorFocusError: colors.transparent,
    colorFocusWarning: colors.transparent,
    fontSizeTiny: '12px',
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    groupLabelTextColor: colors.black,
    heightSmall: '32px',
    heightMedium: '38px',
    heightLarge: '48px',
    iconSize: '24px',
    iconColor: colors.black,
    iconColorDisabled: colors.black,
    iconColorHover: colors.black,
    iconColorPressed: colors.black,
    paddingTiny: '10px',
    paddingSmall: '12px',
    paddingMedium: '20px',
    paddingLarge: '25px',
    placeholderColor: colors.grey.transparent,
    textColor: colors.grey.darker,
    textColorDisabled: colors.grey.darker,
  },
  DatePicker: {
    iconColor: colors.black,
    iconColorDisabled: colors.black,
  },
  Layout: {
    color: colors.bg.DEFAULT,
    textColor: colors.grey.darker,
    siderBorderColor: colors.grey.DEFAULT,
  },
  Message: messageOverrides,
  Modal: {
    color: colors.bg.dark,
    zIndex: 80,
    peers: {
      Card: {
        borderColor: colors.grey.dark,
        borderRadius: '0px',
        paddingSmall: '28px 40px',
        paddingMedium: '32px 64px',
        paddingLarge: '32px 64px',
        paddingHuge: '32px 64px',
      },
      Dialog: {
        border: `1px solid ${colors.grey.dark}`,
        borderRadius: '0px',
        closeColorHover: 'inherit',
        closeMargin: '-24px -24px 0 0',
        contentMargin: '16px 0',
        padding: '64px',
      },
    },
  },
  Pagination: { itemColorDisabled: colors.grey.dark },
  Select: {
    peers: {
      InternalSelection: {
        arrowColor: colors.white,
        arrowSize: '24px',
        border: `1px solid ${colors.grey.dark}`,
        borderActive: `1px solid ${colors.white}`,
        borderFocus: `1px solid ${colors.white}`,
        borderHover: `1px solid ${colors.grey.dark}`,
        borderRadius: '8px',
        boxShadowActive: 'none',
        boxShadowFocus: 'none',
        boxShadowHover: 'none',
        color: colors.bg.light,
        colorActive: colors.bg.light,
        colorDisabled: colors.bg.dark,
        heightLarge: '48px',
        heightMedium: '48px',
        heightSmall: '40px',
        heightTiny: '32px',
      },
      InternalSelectMenu: {
        actionTextColor: colors.black,
        borderRadius: '8px',
        color: colors.grey.DEFAULT,
        paddingSmall: '0px 10px',
        paddingMedium: '0px 10px',
        paddingLarge: '0px 20px',
        optionCheckColor: colors.grey.dark,
        optionColorActive: colors.grey.dark,
        optionColorActivePending: colors.grey.dark,
        optionColorPending: colors.grey.dark,
        optionHeightLarge: '48px',
        optionHeightMedium: '48px',
        optionHeightSmall: '32px',
        optionTextColor: colors.black,
        optionTextColorActive: colors.black,
        optionTextColorPressed: colors.black,
      },
    },
  },
  Table: {
    borderColor: colors.black,
    borderColorModal: colors.black,
    tdColor: colors.transparent,
    tdColorModal: colors.transparent,
  },
  Tag: { colorInfo: colors.grey.dark, fontSizeSmall: '10px', heightSmall: '24px' },

  Tooltip: {
    textColor: colors.white,
  },
  Upload: { draggerBorder: `none`, draggerBorderHover: `none`, draggerColor: colors.bg.light },
};
export const NaiveThemeDark: GlobalThemeOverrides = {
  common: {
    baseColor: colors.bg.dark,
    bodyColor: colors.bg.darker,
    errorColor: colors.pink,
    fontFamily: 'Inter',
    fontSize: '14px',
    infoColor: colors.blue,
    primaryColor: colors.primary,
    primaryColorHover: colors.primary,
    primaryColorPressed: colors.primary,
    successColor: colors.green,
    textColor2: colors.white,
    warningColor: colors.yellow,
  },
  Alert: {
    border: `3px solid ${colors.pink}`,
    borderError: `3px solid ${colors.pink}`,
    borderInfo: `3px solid ${colors.blue}`,
    borderSuccess: `3px solid ${colors.green}`,
    borderWarning: `3px solid ${colors.orange}`,
    borderRadius: '8px',
    color: colors.white,
    colorError: colors.white,
    colorInfo: colors.white,
    colorLoading: colors.white,
    colorSuccess: colors.white,
    colorWarning: colors.white,
    contentTextColor: colors.bg.dark,
    contentTextColorError: colors.bg.dark,
    contentTextColorInfo: colors.bg.dark,
    contentTextColorSuccess: colors.bg.dark,
    contentTextColorWarning: colors.bg.dark,
    textColor: colors.bg.dark,
    textColorError: colors.bg.dark,
    textColorInfo: colors.bg.dark,
    textColorLoading: colors.bg.dark,
    textColorSuccess: colors.bg.dark,
    textColorWarning: colors.bg.dark,
    titleTextColor: colors.bg.dark,
    titleTextColorError: colors.bg.dark,
    titleTextColorInfo: colors.bg.dark,
    titleTextColorSuccess: colors.bg.dark,
    titleTextColorWarning: colors.bg.dark,
    titleFontWeight: '700',
  },
  Button: {
    border: `1px solid ${colors.bg.lighter}`,
    borderDisabled: `1px solid ${colors.bodyDark}`,
    borderDisabledError: `1px solid ${colors.bodyDark}`,
    borderDisabledInfo: `1px solid ${colors.bodyDark}`,
    borderDisabledPrimary: `1px solid ${colors.bodyDark}`,
    borderDisabledSuccess: `1px solid ${colors.bodyDark}`,
    borderDisabledWarning: `1px solid ${colors.bodyDark}`,
    borderError: `1px solid ${colors.bg.lighter}`,
    borderFocusError: `1px solid ${colors.pink}`,
    borderHoverError: `1px solid ${colors.pink}`,
    borderPressedError: `1px solid ${colors.pink}`,
    borderFocus: `1px solid ${colors.bg.lighter}`,
    borderHover: `1px solid ${colors.bg.lighter}`,
    borderPrimary: `1px solid ${colors.bg.lighter}`,
    borderFocusPrimary: `1px solid ${colors.bg.lighter}`,
    borderHoverPrimary: `1px solid ${colors.bg.lighter}`,
    borderPressedPrimary: `1px solid ${colors.bg.lighter}`,
    borderRadiusTiny: '0px',
    borderRadiusSmall: '8px',
    borderRadiusMedium: '8px',
    borderRadiusLarge: '8px',
    colorDisabledPrimary: colors.bg.lighter,
    colorInfo: colors.white,
    colorHover: colors.bg.lighter,
    colorHoverInfo: colors.white,
    colorFocusInfo: colors.white,
    colorPressedInfo: colors.white,
    colorDisabledInfo: colors.white,
    colorQuaternary: 'transparent',
    colorQuaternaryHover: colors.primary,
    colorQuaternaryPressed: colors.primary,
    colorTertiaryHover: colors.bg.lighter,
    colorTertiaryPressed: colors.bg.lighter,
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    fontWeight: 'bold',
    heightMedium: '48px',
    heightLarge: '48px',
    heightSmall: '40px',
    heightTiny: '24px',
    paddingLarge: '8px',
    paddingMedium: '8px 24px',
    paddingSmall: '6px 10px',
    paddingTiny: '1px',
    textColorHover: 'inherit',
    textColorInfo: colors.bg.dark,
    textColorFocus: colors.white,
    textColorError: colors.pink,
    textColorFocusError: colors.pink,
    textColorHoverError: colors.pink,
    textColorGhostHoverError: colors.pink,
    textColorTextHoverError: colors.pink,
    textColorPressedError: colors.pink,
    textColorTextError: colors.pink,
    textColorTertiary: colors.white,
  },
  Card: {
    borderColor: colors.primary,
    borderRadius: '8px',
    color: colors.bg.dark,
    colorEmbedded: colors.bg.dark,
    colorEmbeddedModal: colors.bg.dark,
    colorEmbeddedPopover: colors.bg.dark,
    colorModal: colors.bg.dark,
    colorPopover: colors.bg.dark,
    colorTarget: colors.bg.dark,
    paddingSmall: '32px',
    paddingMedium: '16px 64px 16px 64px',
  },
  DataTable: {
    borderColor: colors.bg.lighter,
    borderColorModal: colors.bg.lighter,
    tdColor: colors.transparent,
    tdColorHover: colors.transparent,
    tdColorHoverModal: colors.transparent,
    tdColorModal: colors.transparent,
    tdTextColor: colors.white,
    thColor: colors.transparent,
    thColorHoverModal: colors.transparent,
    thColorHoverPopover: colors.transparent,
    thColorModal: colors.transparent,
    thColorHover: colors.transparent,
    thFontWeight: '700',
    thTextColor: colors.white,
  },
  DatePicker: {
    iconColor: colors.black,
    iconColorDisabled: colors.black,
  },
  Dialog: {
    border: `1px solid ${colors.bg.lighter}`,
    borderRadius: '0px',
    closeBorderRadius: '50%',
    closeColorHover: colors.white,
    closeColorPressed: colors.white,
    closeIconColor: colors.white,
    closeIconColorPressed: colors.bg.dark,
    closeIconColorHover: colors.bg.dark,
    color: colors.bg.dark,
    contentMargin: '16px 0',
    titleFontSize: '20px',
  },
  Drawer: {
    color: colors.bg.dark,
  },
  Dropdown: {
    borderRadius: '8px',
    color: colors.bg.darker,
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    optionColorActive: colors.bg.lighter,
    optionColorHover: colors.bg.lighter,
    optionTextColor: colors.white,
    optionTextColorHover: colors.white,
    optionTextColorActive: colors.white,
    optionTextColorChildActive: colors.white,
    padding: '16px 12px',
  },
  Form: {
    feedbackFontSizeSmall: '12px',
    feedbackFontSizeMedium: '12px',
    feedbackFontSizeLarge: '14px',
    feedbackHeightSmall: '24px',
    feedbackHeightMedium: '32px',
    feedbackHeightLarge: '40px',
    labelFontSizeTopSmall: '10px',
    labelFontSizeLeftSmall: '10px',
    labelFontSizeLeftMedium: '12px',
    labelFontSizeTopMedium: '12px',
    labelFontSizeLeftLarge: '14px',
    labelFontSizeTopLarge: '14px',
    labelPaddingVertical: '0 0 8px',
    labelTextColor: colors.white,
  },
  Input: {
    border: `1px solid ${colors.bg.lighter}`,
    borderFocus: `1px solid ${colors.white}`,
    borderHover: `1px solid ${colors.body}`,
    borderError: `1px solid ${colors.pink}`,
    borderFocusError: `1px solid ${colors.pink}`,
    borderHoverError: `1px solid ${colors.pink}`,
    borderDisabled: `1px solid ${colors.bodyDark}`,
    borderRadius: '8px',
    boxShadowFocus: 'none',
    boxShadowFocusError: 'none',
    boxShadowFocusWarning: 'none',
    caretColor: colors.bg.darker,
    clearSize: '24px',
    color: colors.bg.DEFAULT,
    colorDisabled: colors.bg.DEFAULT,
    colorFocus: colors.bg.light,
    colorFocusError: colors.bg.light,
    colorFocusWarning: colors.bg.light,
    fontSizeTiny: '12px',
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    groupLabelTextColor: colors.white,
    heightSmall: '40px',
    heightMedium: '48px',
    heightLarge: '48px',
    iconSize: '24px',
    paddingTiny: '10px',
    paddingSmall: '12px',
    paddingMedium: '20px',
    paddingLarge: '25px',
    placeholderColor: colors.body,
    textColor: colors.black,
    textColorDisabled: colors.bodyDark,
  },
  Layout: {
    color: colors.bg.bg,
    textColor: colors.white,
    siderBorderColor: colors.bg.lighter,
  },
  Message: messageOverrides,
  Modal: {
    color: colors.bg.dark,
    zIndex: 80,
    peers: {
      Card: {
        borderColor: colors.bg.lighter,
        borderRadius: '0px',
        paddingSmall: '28px 40px',
        paddingMedium: '32px 64px',
        paddingLarge: '32px 64px',
        paddingHuge: '32px 64px',
      },
      Dialog: {
        border: `1px solid ${colors.bg.lighter}`,
        borderRadius: '0px',
        closeColorHover: 'inherit',
        closeMargin: '-24px -24px 0 0',
        contentMargin: '16px 0',
        padding: '64px',
      },
    },
  },
  Pagination: { itemColorDisabled: colors.bodyDark },
  Popover: { arrowHeight: '14px', spaceArrow: '14px', textColor: colors.white },
  Select: {
    peers: {
      InternalSelection: {
        arrowColor: colors.white,
        arrowSize: '24px',
        border: `1px solid ${colors.bg.lighter}`,
        borderActive: `1px solid ${colors.white}`,
        borderFocus: `1px solid ${colors.white}`,
        borderHover: `1px solid ${colors.body}`,
        borderRadius: '8px',
        boxShadowActive: 'none',
        boxShadowFocus: 'none',
        boxShadowHover: 'none',
        color: colors.bg.light,
        colorActive: colors.bg.light,
        colorDisabled: colors.bg.dark,
        heightLarge: '48px',
        heightMedium: '48px',
        heightSmall: '40px',
        heightTiny: '32px',
      },
      InternalSelectMenu: {
        actionTextColor: colors.white,
        borderRadius: '8px',
        color: colors.bg.darker,
        paddingSmall: '0px 10px',
        paddingMedium: '0px 10px',
        paddingLarge: '0px 20px',
        optionCheckColor: colors.bg.lighter,
        optionColorActive: colors.bg.lighter,
        optionColorActivePending: colors.bg.lighter,
        optionColorPending: colors.bg.lighter,
        optionHeightLarge: '48px',
        optionHeightMedium: '48px',
        optionHeightSmall: '32px',
        optionTextColor: colors.white,
        optionTextColorActive: colors.white,
        optionTextColorPressed: colors.white,
      },
    },
  },
  Table: {
    borderColor: colors.bg.light,
    borderColorModal: colors.bg.light,
    tdColor: colors.transparent,
    tdColorModal: colors.transparent,
  },
  Tag: { colorInfo: colors.bg.lighter, fontSizeSmall: '10px', heightSmall: '24px' },
  Tooltip: {
    textColor: colors.white,
  },
  Upload: { draggerBorder: `none`, draggerBorderHover: `none`, draggerColor: colors.bg.light },
};
